### ISSUE TITLE
setup main mvp studio creds in a google cloud storage bucket and link to it in slack

### ISSUE THREAD

**Issue by slively** [MVPStudio/main#11]

**Comment by oliverdain** [comment]
```
gsutil rsync -r gs://passwords.mvpstudio.org .
```

should do the trick to copy all passwords from the cloud to local. Haven't put any actual passwords in there yet.

**Comment by oliverdain** [comment]
Waiting for confirmation from others that this worked before closing

**Comment by slively** [comment]
a bunch of stuff is in there now
