### ISSUE TITLE
Deposit $150 from oliver

### ISSUE THREAD

**Issue by markdav-is** [MVPStudio/main#28]
<hr /><div align="center"><img alt="Screenshot uploaded with GitShot" src="https://i.imgur.com/8WYZTkm.png" width="300.0" height="649.6" align="center" /><br><br>Documented with <a href="https://goo.gl/oZUi2a">GitShot</a></div><hr />

To offset was costs

**Comment by oliverdain** [comment]
@nohorse why is this a task - looks like it was deposited and is done...
